# Use Python base image
FROM python:3.10

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastapi uvicorn \
    langchain langchain-community langchain-ollama langchain-chroma langchain-huggingface pdfplumber rank-bm25

# Copy everything from the project directory to /app inside the container
COPY server.py /app

# Run the FastAPI app
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
