# Use Python base image
FROM python:3.10

WORKDIR /app

# Copy everything from the project directory to /app inside the container
COPY server.py /app

# Install dependencies
RUN pip install --no-cache-dir fastapi uvicorn \
    langchain langchain_ollama langchain_chroma langchain_huggingface

# Run the FastAPI app
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
